/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package titutorial.demo;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="Demo", id="titutorial.demo", propertyAccessors = { "hintText", "value" })
public class DemoModule extends KrollModule
{
	//constants
    @Kroll.constant
    public static final int PAGE_LIMIT = 10;
    
	// Standard Debugging variables
	private static final String TAG = "DemoModule";
	private String tag = "default";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public DemoModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}


	// Methods
	@Kroll.method
	public String addStrings(String a, String b)
	{
		return a.concat(b);
	}
	
	// Properties
	@Kroll.getProperty @Kroll.method
	public String getTag() {
	    return tag;
	}
	 
	@Kroll.setProperty @Kroll.method
	public void setTag(String t) {
		tag = t;
	}

}

